config/routes.rb
Rails.application.routes.draw do

  devise_for :groups
  devise_for :users

  root to: 'pages#index'

  post '/points/:id/upvote', to: 'points#upvote', as: 'upvote_point'
  post '/points/:id/downvote', to: 'points#downvote', as: 'downvote_point'

  post '/contributions/:id/upvote', to: 'contributions#upvote', as: 'upvote_contribution'
  post '/contributions/:id/downvote', to: 'contributions#downvote', as: 'downvote_contribution'

  post '/comments/:id/upvote', to: 'comments#upvote', as: 'upvote_comment'
  post '/comments/:id/downvote', to: 'comments#downvote', as: 'downvote_comment'

  get '/points/:id/contributions', to: 'contributions#index'

  post '/points', to: 'points#create'
  post '/contributions', to: 'contributions#create'
  post '/comments', to: 'comments#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  def author
    author = User.find_by(id: user_id) || author = Group.find_by(id: group_id)
  end

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base

  has_many :comments

  def author
    author = User.find_by(id: user_id) || author = Group.find_by(id: group_id)
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :points
  has_many :contributions
  has_many :comments

end

app/models/point.rb
class Point < ActiveRecord::Base

  has_many :contributions

  def author
    author = User.find_by(id: user_id) || author = Group.find_by(id: group_id)
  end

  def contributions_and_comments
    contributions.map do |contribution|
      {contribution: contribution, comments: contribution.comments.order(:score).reverse }
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :points
  has_many :contributions
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def create
    @contribution = Contribution.find(params[:contribution_id])
    @contribution.comments.create(text: params[:text], user_id: current_user.id)
    redirect_to :back
  end

  def upvote
    comment = Comment.find(params[:id])
    comment.score += 1
    comment.save
    redirect_to :back
  end

  def downvote
    comment = Comment.find(params[:id])
    comment.score -= 1
    comment.save
    redirect_to :back
  end

end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def index
    point_id = params[:id]
    @point = Point.find(point_id)
    @contributions = @point.contributions_and_comments
  end

  def create
    current_user.contributions.create(point_id: params[:point_id], title: params[:title], text: params[:text], image_url: params[:image_url])
    redirect_to :back
  end

  def upvote
    contribution = Contribution.find(params[:id])
    contribution.score += 1
    contribution.save
    redirect_to :back
  end

  def downvote
    contribution = Contribution.find(params[:id])
    contribution.score -= 1
    contribution.save
    redirect_to :back
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    redirect_to new_user_session_path if !user_signed_in?
    @points = Point.all.order(:score).reverse
  end

end

app/controllers/points_controller.rb
class PointsController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def create
    title = params[:title]
    description = params[:description]
    tag = params[:tag]
    image_url = params[:image_url]
    current_user.points.create(title: title, description: description, tag: tag, image_url: image_url)
    redirect_to :back
  end

  def upvote
    point = Point.find(params[:id])
    point.score += 1
    point.save
    redirect_to :back
  end

  def downvote
    point = Point.find(params[:id])
    point.score -= 1
    point.save
    redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/contributions/index.html.erb
<header>
  <h1><%= @point.title %></h1>
</header>
<p><%= @point.description %></p>
<p>score: <%= @point.score %></p>
<p>tag: <%= @point.tag %></p>
<p>author: <%= @point.author.name %></p>
<%= button_to "upvote", upvote_point_path(@point.id) %>
<%= button_to "downvote", downvote_point_path(@point.id) %>

<h2>Contributions</h2>

<form action='/contributions', method='post'>
  <input type='hidden' name='point_id' value='<%=@point.id%>'>
  Title:<br>
  <input type="text" name="title">
  <br>
  Description:<br>
  <input type="text" name="text">
  <br>
  Image Url:<br>
  <input type="text" name="image_url">
  <input type='submit' />
</form>

<ul>
  <% @contributions.each do |contribution| %>
    <li>
      <img src="<%= contribution[:contribution].image_url %>" />
      <h2><%= contribution[:contribution].title %></h2>
      <p><%= contribution[:contribution].text %></p>
      <p>score: <%= contribution[:contribution].score %></p>
      <p>author: <%= contribution[:contribution].author.name %></p>
      <%= button_to "upvote", upvote_contribution_path(contribution[:contribution].id) %>
      <%= button_to "downvote", downvote_contribution_path(contribution[:contribution].id) %>
      <ul>
        <form action='/comments', method='post'>
          <h3>Add Comment</h3>
          <input type='hidden' name='contribution_id' value='<%=contribution[:contribution].id%>'>
          Text:<br>
          <input type="text" name="text">
          <input type='submit' />
        </form>
        <% contribution[:comments].each do |comment| %>
          <li>
            <p><%= comment.text %></p>
            <p>score: <%= comment.score %></p>
            <%= button_to "upvote", upvote_comment_path(comment.id) %>
            <%= button_to "downvote", downvote_comment_path(comment.id) %>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Points</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" src="/normalize.css"/>
  <link rel="stylesheet" type="text/css" src="/main-skeleton.css"/>
  <link rel="stylesheet" type="text/css" src="/main.css" media="screen, handheld"/>
  <!-- <link rel="stylesheet" type="text/css" src="/enhanced.css" media="screen and (min-width: 40.5em)"/> for big screens-->
  <!--[if (lt IE 9)&(!IEMobile)]>
<link rel="stylesheet" type="text/css" href="enhanced.css" />
<![endif]-->
</head>
<body id="page">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/pages/index.html.erb
<header class="app-bar">
  <h1 class="logo">Points</h1>
  <ul id="nav-anchors" class="nav-anchors">
    <li><a href="#nav" id="menu-anchor">Menu</a></li>
  </ul>
</header>
<nav id="nav" class="nav reveal">
  <form id="search" action="#" method="post" class="search reveal">
    <fieldset>
      <legend>Search points</legend>
      <label for="search-site">Search points</label>
      <input type="search" id="search-site" placeholder="Search points" class="btn">
      <input type="submit" value="Search">
    </fieldset>
  </form>
  <ul class="nav-list sort-btns">
    <li class="btn"><a href="#"> Important</a></li>
    <li class="btn"><a href="#">Council</a></li>
    <li class="btn"><a href="#">Community</a></li>
    <li class="btn"><a href="#">New</a></li>
  </ul>
  <ul class="nav-list site-nav" role="navigation">
    <li class="about btn"><a href="#">Why is this great?</a></li>
    <li class="you btn"><a href="#">Why we need you</a></li>
  </ul>
</nav>
<div class="content points" role="main">


  <div id="new-point" class="reveal btn call-to-action">
    <div id="new-point-anchor" class="user-input-reveal new-point-anchor btn">
      <a href="#new-point">I have a new point!</a>
    </div>
    <form class='new-point-form' action='/points', method='post'>
      Title:<br>
      <input type="text" name="title">
      <br>
      Description:<br>
      <input type="textarea" rows="4" name="description">
      <br>
      <!-- Tag:<br> -->
      <!-- <input type="text" name="tag">
      <br> -->
      Image-Url:<br>
      <input type="text" name="image_url">
      <br>
      <input type='submit' class='btn call-to-action' />
    </form>
  </div>

  <ul>
    <% @points.each do |point| %>
      <li class="one-point btn">
        <div class="point-title">
          <h2><%= point.title %></h2>
        </div>
        <div class="vertical-aligner">
          <div class="icon-bar">
            <%= button_to "upvote", upvote_point_path(point.id) %>
            <p><%= point.score %></p>
            <button class="share" href="#">
            <!-- <p>author: <%= point.author.email %></p> -->
            <!-- <%= button_to "downvote", downvote_point_path(point.id) %> -->
          </div>
          <a href="/points/<%=point.id%>/contributions" class="vertical-aligner">
            <div class="point-overview">
              <p><%= point.description %></p>
            </div>
            <div class="point-image">
              <img src="<%=point.image_url%>">
            </div>
            <!-- <p>tag: <%= point.tag %></p> -->
          </a>
        </div>
      </li>
        <!-- <% if point.image_url %>
        <% end %> -->
    <% end %>
  </ul>
</div>
<footer class="container">
  <ul>
    <li><p>Ka pai - you're up with the play!</p></li>
    <li><a href="#page" class="top btn">&nbsp;&nbsp;&nbsp;&nbsp;to top</a></li>
  </ul>
</footer>